portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("", include("users.urls")),
    path("", user_views.dashboard, name="dashboard"),
]

projects/urls.py
from django.urls import path
from projects import views

app_name = "projects"

urlpatterns = [
    path("", views.all_projects, name="all_projects"),
    path("<int:pk>", views.project_detail, name="project_detail"),
]

users/urls.py
from django.urls import path, include, reverse_lazy
from users import views
from django.contrib.auth import views as auth_views

# from django.contrib.

# app_name = "users"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    # path(
    #     "accounts/password_change/",
    #     auth_views.PasswordChangeView.as_view(success_url="done/"),
    #     name="password_change",
    # ),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
]

# from django.contrib.auth.urls import urlpatterns

projects/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    # image = models.FilePathField(path="/projects/img")
    image = models.CharField(max_length=100)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

projects/views.py
from django.shortcuts import render
from projects.models import Project

# Create your views here.


def project_list(request):
    return render(request, "projects/index.html")


def all_projects(request):
    projects = Project.objects.all()
    # print(projects)
    return render(request, "projects/all_projects.html", {"projects": projects})


def project_detail(request, pk):
    project = Project.objects.get(pk=pk)
    return render(request, "projects/project_detail.html", {"project": project})

users/views.py
from django.shortcuts import render
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.urls import reverse
from users.forms import CustomUserCreationForm

# from users.forms import CustomUserCreationForm

# Create your views here.


def dashboard(request):
    return render(request, "users/dashboard.html")


def register(request):
    if request.method == "GET":
        return render(
            request, "registration/register.html", {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse("dashboard"))

portfolio/templates/base.html
{% block page_content %}{% endblock %}

projects/templates/projects/all_projects.html
{% extends "projects/base.html" %}
{% load static %}
{% block content %}
    <h1>Projects</h1>
    <div class="row">
        {% for project in projects %}
            <div class="col-md-4">
                <div class="card mb-2">
                    <img class="card-img-top" src="{% static project.image %}">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.title }}</h5>
                        <p class="card-text">{{ project.description }}</p>
                        <a href="{% url 'projects:project_detail' project.pk %}"
                           class="btn btn-primary">Read More</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

projects/templates/projects/base.html
<!DOCTYPE html>
<head>
  <html lang="en">
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'projects:all_projects' %}">Portfolio</a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse"     id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'projects:all_projects' %}">Portfolio Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>

projects/templates/projects/project_detail.html
{% extends "projects/base.html" %}
{% load static %}

{% block content %}
<h1>{{ project.title }}</h1>
<div class="row">
    <div class="col-md-8">
        <img src="{% static project.image %}" alt="" width="100%">
    </div>
    <div class="col-md-4">
        <h5>About the project:</h5>
        <p>{{ project.description }}</p>
        <br>
        <h5>Technology used:</h5>
        <p>{{ project.technology }}</p>
    </div>
</div>
{% endblock %}

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Portfolio</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

  

  <div class="container">
    {% block content %}

    {% endblock %}
  </div>

</body>

<style>
  label, input {
    display: block;
  }

  span.helptext{
    display: none;
  }
</style>

</html>

users/templates/users/dashboard.html
{% extends "users/base.html" %}
{% block content %}
    <h1>Hello, {{ user.username|default:"Guest" }}  !!</h1>
    <div>
        {% if user.is_authenticated %}
            <div>
                <a href="{% url 'logout' %}">Logout</a>
            </div>
            <div>
                <a href="{% url 'password_change' %}">Change Password</a>
            </div>
        {% else %}
            <div>
                <a href="{% url 'login' %}">Login</a>
            </div>
            <div>
                <a href="{% url 'password_reset' %}">Reset Password</a>
            </div>
        {% endif %}
    </div>
    <div>
        <a href="{% url 'projects:all_projects' %}">See some projects here!</a>
    </div>
{% endblock content %}